version: '3'
services:
  server:
    container_name: server
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - '8085:8000'
    volumes:
      - ./src:/go/src
    restart: always
    tty: true
