CREATE TABLE tasks (
    taskId INT AUTO_INCREMENT NOT NULL PRIMARY KEY,
    `status` VARCHAR(50),
    title VARCHAR(250),
    `desc` VARCHAR(250),
    createdDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
